#[derive(FromPrimitive)]
pub enum JamParams {
    ChanGain1 = 0,
    ChanGain2,
    ChanGain3,
    ChanGain4,
    ChanGain5,
    ChanGain6,
    ChanGain7,
    ChanGain8,
    ChanGain9,
    ChanGain10,
    ChanGain11,
    ChanGain12,
    ChanGain13,
    ChanGain14,
    MasterVol,
    InputMonitor,
    Room0,
    Room1,
    Room2,
    ReverbChanOne,
    ReverbMix,
    RoomChange,
    Disconnect,
    HPFOn,
    HPFOff,
    ReverbOne,
    ReverbTwo,
    GetConfigJson,
    SetEffectConfig,
    InsertPedal,
    DeletePedal,
    MovePedal,
    LoadBoard,
    TuneChannel,
    MetronomeVolume,
    SetFader,
    MuteToRoom,
    ConnectionKeepAlive,
    SetBufferSize,
    Count,
    SetAudioInput = 1000,
    SetAudioOutput,
    ListAudioConfig,
    CheckForUpdate,
    RandomCommand,
    GetPedalTypes,
    SetUpdateInterval,
    RebootDevice = 9998,
    ShutdownDevice = 9999,
}
